/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LatihanGUI;

/**
 *
 * @author User
 */
public class Latihan3 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan3
     */
    public Latihan3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idtb = new javax.swing.JTextField();
        jeniskelamin = new javax.swing.JLabel();
        idsaran = new javax.swing.JTextField();
        idbb = new javax.swing.JTextField();
        perempuan = new javax.swing.JRadioButton();
        lakilaki = new javax.swing.JRadioButton();
        keluar = new javax.swing.JButton();
        hitung = new javax.swing.JButton();
        ulangi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idnama = new javax.swing.JTextField();
        idideal = new javax.swing.JTextField();
        idanalisa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jLabel2.setText("CEK KESEHATAN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 0, 180, 40);

        jLabel3.setText("Nama");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 30, 90, 40);

        jLabel4.setText("Berat Badan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 60, 90, 40);

        jLabel5.setText("Tinggi Badan");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 100, 90, 40);
        getContentPane().add(idtb);
        idtb.setBounds(140, 110, 210, 30);

        jeniskelamin.setText("Jenis Kelamin");
        getContentPane().add(jeniskelamin);
        jeniskelamin.setBounds(30, 140, 90, 40);

        idsaran.setText("saran?");
        idsaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idsaranActionPerformed(evt);
            }
        });
        getContentPane().add(idsaran);
        idsaran.setBounds(60, 310, 320, 30);
        getContentPane().add(idbb);
        idbb.setBounds(140, 70, 210, 30);

        perempuan.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(perempuan);
        perempuan.setText("Perempuan");
        getContentPane().add(perempuan);
        perempuan.setBounds(280, 150, 130, 23);

        lakilaki.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(lakilaki);
        lakilaki.setText("Laki-laki");
        getContentPane().add(lakilaki);
        lakilaki.setBounds(140, 150, 110, 23);

        keluar.setBackground(new java.awt.Color(204, 255, 204));
        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(300, 180, 80, 23);

        hitung.setBackground(new java.awt.Color(204, 255, 204));
        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        getContentPane().add(hitung);
        hitung.setBounds(60, 180, 90, 20);

        ulangi.setBackground(new java.awt.Color(204, 255, 204));
        ulangi.setText("Ulangi");
        ulangi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulangiActionPerformed(evt);
            }
        });
        getContentPane().add(ulangi);
        ulangi.setBounds(190, 180, 80, 23);

        jLabel1.setText("kg");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(360, 80, 34, 14);

        jLabel7.setText("Berat badan ideal anda adalah :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 220, 190, 14);

        jLabel8.setText("Hasil Analisis Kesehatan");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 250, 150, 14);

        idnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idnamaActionPerformed(evt);
            }
        });
        getContentPane().add(idnama);
        idnama.setBounds(140, 30, 240, 30);
        getContentPane().add(idideal);
        idideal.setBounds(260, 220, 40, 30);

        idanalisa.setText("?");
        idanalisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idanalisaActionPerformed(evt);
            }
        });
        getContentPane().add(idanalisa);
        idanalisa.setBounds(60, 270, 320, 30);

        jLabel9.setText("cm");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(360, 110, 20, 14);

        jLabel10.setText("kg");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(310, 220, 30, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LatihanGUI/bg.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(-10, -90, 1670, 780);

        setBounds(0, 0, 495, 420);
    }// </editor-fold>//GEN-END:initComponents

    private void idsaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idsaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idsaranActionPerformed

    private void idanalisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idanalisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idanalisaActionPerformed

    private void idnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idnamaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_idnamaActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
         double t, b, h = 0;
         
         //untuk mengambil nilai tinggi dan berat serta nama
        t = Double.valueOf(idtb.getText());
        b = Double.valueOf(idbb.getText());
        String nm = idnama.getText();
        //pilihan jenis kelamin
        if (lakilaki.isSelected()){
            h = (t-100);
        
        }else if (perempuan.isSelected()){
        h = (t-104);
        }
        String temp = Double.toString(h);
    
        
        //logika untuk analisa hasil kesehatan
        if(h>b){
            idideal.setText(temp);
            idanalisa.setText("Maaf " + nm + " anda kekurangan berat badan");
            idsaran.setText("Makan yang banyak dan bergizi");
        }else if (h<b){
            idideal.setText(temp);
            idanalisa.setText("Maaf " + nm + " anda kelebihan berat badan");
            idsaran.setText("Perbanyak olahraga dan mengatur pola makan");
        }else{
            idideal.setText(temp);
            idanalisa.setText("Berat badan anda sudah");
            idsaran.setText("Pertahankan");
        }
        
        
        
    }//GEN-LAST:event_hitungActionPerformed

    private void ulangiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulangiActionPerformed
        // TODO add your handling code here:
        idnama.setText(" ");
        idbb.setText(" ");
        idtb.setText(" ");
        lakilaki.setSelected(false);
        perempuan.setSelected(false);
        idideal.setText(" ");
        idanalisa.setText(" ");
        idsaran.setText(" ");
        
        
        
        
    }//GEN-LAST:event_ulangiActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
         dispose();
        //System.exit(1);
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton hitung;
    private javax.swing.JTextField idanalisa;
    private javax.swing.JTextField idbb;
    private javax.swing.JTextField idideal;
    private javax.swing.JTextField idnama;
    private javax.swing.JTextField idsaran;
    private javax.swing.JTextField idtb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jeniskelamin;
    private javax.swing.JButton keluar;
    private javax.swing.JRadioButton lakilaki;
    private javax.swing.JRadioButton perempuan;
    private javax.swing.JButton ulangi;
    // End of variables declaration//GEN-END:variables
}
