/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LatihanGUI;

/**
 *
 * @author User
 */
public class Latihan2 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan2
     */
    public Latihan2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        pilihanJurusan = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rdbTKJ = new javax.swing.JRadioButton();
        rdbRPL = new javax.swing.JRadioButton();
        varAbsen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        varNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();
        animator = new javax.swing.JCheckBox();
        programming = new javax.swing.JCheckBox();
        editor = new javax.swing.JCheckBox();
        designer = new javax.swing.JCheckBox();
        remove = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\Pictures\\Sekolah\\9highclass\\IMG-20170803-WA0009.jpg")); // NOI18N
        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nama");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(32, 72, 27, 14);

        jLabel2.setText("BIODATA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 40, 70, 14);

        pilihanJurusan.add(rdbTKJ);
        rdbTKJ.setText("TKJ");
        rdbTKJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTKJActionPerformed(evt);
            }
        });
        getContentPane().add(rdbTKJ);
        rdbTKJ.setBounds(110, 130, 43, 23);

        pilihanJurusan.add(rdbRPL);
        rdbRPL.setText("RPL");
        rdbRPL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbRPLActionPerformed(evt);
            }
        });
        getContentPane().add(rdbRPL);
        rdbRPL.setBounds(170, 130, 93, 23);
        getContentPane().add(varAbsen);
        varAbsen.setBounds(110, 100, 200, 20);

        jLabel3.setText("Absen");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 100, 34, 14);

        varNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varNamaActionPerformed(evt);
            }
        });
        getContentPane().add(varNama);
        varNama.setBounds(110, 70, 200, 20);

        jLabel4.setText("Jurusan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 130, 60, 14);

        jLabel5.setText("Hobi");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 160, 34, 14);

        hasil.setColumns(20);
        hasil.setRows(5);
        jScrollPane1.setViewportView(hasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 290, 240, 96);

        animator.setText("Animator");
        getContentPane().add(animator);
        animator.setBounds(200, 160, 110, 23);

        programming.setText("Programming");
        getContentPane().add(programming);
        programming.setBounds(100, 160, 110, 23);

        editor.setText("Video Editing");
        editor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editorActionPerformed(evt);
            }
        });
        getContentPane().add(editor);
        editor.setBounds(200, 180, 110, 23);

        designer.setText("Designer");
        getContentPane().add(designer);
        designer.setBounds(100, 180, 110, 23);

        remove.setText("Remove");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        getContentPane().add(remove);
        remove.setBounds(170, 230, 71, 23);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(270, 230, 51, 23);

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit);
        submit.setBounds(70, 230, 65, 23);

        jLabel6.setText("Hasil");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 270, 34, 14);

        setBounds(0, 0, 546, 450);
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        dispose();
        //System.exit(1);
    }//GEN-LAST:event_exitActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code here:
        varNama.setText(" ");
        varAbsen.setText(" ");
        pilihanJurusan.clearSelection();
        programming.setSelected(false);
        designer.setSelected(false);
        animator.setSelected(false);
        editor.setSelected(false);
    }//GEN-LAST:event_removeActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        String nama = varNama.getText();
        String absen = varAbsen.getText();
        String jurusan;
        String hobi=" ";
        
        //Untuk pilihan jurusan
        if(rdbRPL.isSelected()){
        jurusan = "RPL";
        }else if (rdbTKJ.isSelected());
        jurusan = "TKJ";
    
        
        //Untuk pilihan checkbox
        if (programming.isSelected());
        hobi=programming.getText()+",";
        if (designer.isSelected());
        hobi=designer.getText()+",";
        if (animator.isSelected());
        hobi=animator.getText()+",";
        if (editor.isSelected());
        hobi=editor.getText()+",";
        
        //Untuk hasil
        hasil.setText("Nama anda : "+ nama+"\n Absen nama:"+absen+"\nJurusan anda:"+jurusan+"\n Hobi anda:"+ hobi);
        
        
        
    }//GEN-LAST:event_submitActionPerformed

    private void rdbTKJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTKJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbTKJActionPerformed

    private void editorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editorActionPerformed

    private void varNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varNamaActionPerformed

    private void rdbRPLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbRPLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbRPLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox animator;
    private javax.swing.JCheckBox designer;
    private javax.swing.JCheckBox editor;
    private javax.swing.JButton exit;
    private javax.swing.JTextArea hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup pilihanJurusan;
    private javax.swing.JCheckBox programming;
    private javax.swing.JRadioButton rdbRPL;
    private javax.swing.JRadioButton rdbTKJ;
    private javax.swing.JButton remove;
    private javax.swing.JButton submit;
    private javax.swing.JTextField varAbsen;
    private javax.swing.JTextField varNama;
    // End of variables declaration//GEN-END:variables
}
