/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LatihanGUI;

/**
 *
 * @author User
 */
public class Latihan1 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan1
     */
    public Latihan1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bilangan1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Bilangan2 = new javax.swing.JTextField();
        ButtonKali = new javax.swing.JButton();
        ButtonBagi = new javax.swing.JButton();
        ButtonJumlah = new javax.swing.JButton();
        ButtonKurang = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Hasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 51, 0));
        jPanel1.setLayout(null);

        jLabel1.setText("Kalkulator Sederhana");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(260, 70, 310, 40);

        bilangan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilangan1ActionPerformed(evt);
            }
        });
        jPanel1.add(bilangan1);
        bilangan1.setBounds(230, 130, 140, 30);

        jLabel2.setText("Bilangan 1");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 130, 120, 30);

        jLabel3.setText("Bilangan 2");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 180, 60, 14);

        Bilangan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bilangan2ActionPerformed(evt);
            }
        });
        jPanel1.add(Bilangan2);
        Bilangan2.setBounds(230, 170, 140, 30);

        ButtonKali.setText("x");
        ButtonKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKaliActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonKali);
        ButtonKali.setBounds(170, 230, 40, 30);

        ButtonBagi.setText("/");
        ButtonBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBagiActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonBagi);
        ButtonBagi.setBounds(240, 230, 37, 30);

        ButtonJumlah.setText("+");
        ButtonJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonJumlahActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonJumlah);
        ButtonJumlah.setBounds(310, 230, 40, 30);

        ButtonKurang.setText("-");
        ButtonKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKurangActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonKurang);
        ButtonKurang.setBounds(380, 230, 37, 30);

        jLabel4.setText("Hasil");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(300, 300, 40, 14);

        Hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasilActionPerformed(evt);
            }
        });
        jPanel1.add(Hasil);
        Hasil.setBounds(250, 320, 130, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 740, 500);

        setBounds(0, 0, 728, 524);
    }// </editor-fold>//GEN-END:initComponents

    private void bilangan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilangan1ActionPerformed
        // TODO add your handling code here:
        int bil1 = Integer.parseInt(bilangan1.getText());
        int bil2 = Integer.parseInt(Bilangan2.getText());
        int hasil = bil1*bil2;
        
        Hasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_bilangan1ActionPerformed

    private void ButtonKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKaliActionPerformed
        // TODO add your handling code here:
        int bil1 = Integer.parseInt(bilangan1.getText());
        int bil2 = Integer.parseInt(Bilangan2.getText());
        int hasil = bil1*bil2;
        
        Hasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_ButtonKaliActionPerformed

    private void Bilangan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bilangan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bilangan2ActionPerformed

    private void HasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasilActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_HasilActionPerformed

    private void ButtonBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBagiActionPerformed
        // TODO add your handling code here:
          int bil1 = Integer.parseInt(bilangan1.getText());
        int bil2 = Integer.parseInt(Bilangan2.getText());
        int hasil = bil1/bil2;
        
        Hasil.setText(String.valueOf(hasil));
      
    }//GEN-LAST:event_ButtonBagiActionPerformed

    private void ButtonJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonJumlahActionPerformed
        // TODO add your handling code here:
          int bil1 = Integer.parseInt(bilangan1.getText());
        int bil2 = Integer.parseInt(Bilangan2.getText());
        int hasil = bil1+bil2;
        
        Hasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_ButtonJumlahActionPerformed

    private void ButtonKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKurangActionPerformed
        // TODO add your handling code here:
          int bil1 = Integer.parseInt(bilangan1.getText());
        int bil2 = Integer.parseInt(Bilangan2.getText());
        int hasil = bil1-bil2;
        
        Hasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_ButtonKurangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bilangan2;
    private javax.swing.JButton ButtonBagi;
    private javax.swing.JButton ButtonJumlah;
    private javax.swing.JButton ButtonKali;
    private javax.swing.JButton ButtonKurang;
    private javax.swing.JTextField Hasil;
    private javax.swing.JTextField bilangan1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
