/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LatihanGUI;

/**
 *
 * @author User
 */
public class latihan5 extends javax.swing.JFrame {

    /**
     * Creates new form latihan5
     */
    public latihan5(String nama, String absen, String jurusan, String alamat, String kls) {
        initComponents();
        idnama.setText(nama);
        idabsen.setText(absen);
        idjurusan.setText(jurusan);
        idalamat.setText(alamat);
        idkelas.setText(kls);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idnama = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idabsen = new javax.swing.JLabel();
        idjurusan = new javax.swing.JLabel();
        idalamat = new javax.swing.JLabel();
        idkelas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        idnama.setText("NAMA");
        getContentPane().add(idnama);
        idnama.setBounds(70, 80, 100, 14);

        jLabel2.setText("HASIL BIODATA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 30, 190, 14);

        idabsen.setText("ABSEN");
        getContentPane().add(idabsen);
        idabsen.setBounds(70, 110, 120, 14);

        idjurusan.setText("JURUSAN");
        getContentPane().add(idjurusan);
        idjurusan.setBounds(70, 140, 140, 14);

        idalamat.setText("ALAMAT");
        getContentPane().add(idalamat);
        idalamat.setBounds(70, 170, 130, 14);

        idkelas.setText("KELAS");
        getContentPane().add(idkelas);
        idkelas.setBounds(70, 200, 160, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LatihanGUI/bg3.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 470, 340);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(latihan5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(latihan5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(latihan5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(latihan5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idabsen;
    private javax.swing.JLabel idalamat;
    private javax.swing.JLabel idjurusan;
    private javax.swing.JLabel idkelas;
    private javax.swing.JLabel idnama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
